[2025-02-08T13:01:06.238+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-08T13:01:06.265+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_user manual__2025-02-08T13:01:02.752567+00:00 [queued]>
[2025-02-08T13:01:06.387+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_user manual__2025-02-08T13:01:02.752567+00:00 [queued]>
[2025-02-08T13:01:06.387+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-02-08T13:01:06.398+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): MusicStream_load_user> on 2025-02-08 13:01:02.752567+00:00
[2025-02-08T13:01:06.406+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=827) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T13:01:06.407+0000] {standard_task_runner.py:63} INFO - Started process 829 to run task
[2025-02-08T13:01:06.405+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_MusicStreamPipeline', 'MusicStream_load_user', 'manual__2025-02-08T13:01:02.752567+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpql1m7qi0']
[2025-02-08T13:01:06.407+0000] {standard_task_runner.py:91} INFO - Job 211: Subtask MusicStream_load_user
[2025-02-08T13:01:06.443+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_MusicStreamPipeline.MusicStream_load_user manual__2025-02-08T13:01:02.752567+00:00 [running]> on host 35ef1ca6714b
[2025-02-08T13:01:06.516+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Huynh Thanh Duong' AIRFLOW_CTX_DAG_ID='etl_MusicStreamPipeline' AIRFLOW_CTX_TASK_ID='MusicStream_load_user' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T13:01:02.752567+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-08T13:01:02.752567+00:00'
[2025-02-08T13:01:06.518+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-08T13:01:06.579+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-08T13:01:06.580+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etls/load.py", line 27, in load_dim_Users
    cur.execute(user_table_insert, (row.userId, row.firstName, row.lastName, row.gender, row.level))
psycopg2.errors.UndefinedTable: relation "dim_user" does not exist
LINE 1: INSERT INTO dim_user(user_id, first_name, last_name, gender,...
                    ^

[2025-02-08T13:01:06.589+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl_MusicStreamPipeline, task_id=MusicStream_load_user, execution_date=20250208T130102, start_date=20250208T130106, end_date=20250208T130106
[2025-02-08T13:01:06.599+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 211 for task MusicStream_load_user (relation "dim_user" does not exist
LINE 1: INSERT INTO dim_user(user_id, first_name, last_name, gender,...
                    ^
; 829)
[2025-02-08T13:01:06.620+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-08T13:01:06.634+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T13:01:06.637+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
