[2025-02-08T12:29:39.865+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-08T12:29:39.891+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_time manual__2025-02-08T12:29:37.983005+00:00 [queued]>
[2025-02-08T12:29:39.899+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_time manual__2025-02-08T12:29:37.983005+00:00 [queued]>
[2025-02-08T12:29:39.899+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-02-08T12:29:40.007+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): MusicStream_load_time> on 2025-02-08 12:29:37.983005+00:00
[2025-02-08T12:29:40.013+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_MusicStreamPipeline', 'MusicStream_load_time', 'manual__2025-02-08T12:29:37.983005+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpxzyni2mr']
[2025-02-08T12:29:40.015+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=323) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T12:29:40.015+0000] {standard_task_runner.py:91} INFO - Job 171: Subtask MusicStream_load_time
[2025-02-08T12:29:40.016+0000] {standard_task_runner.py:63} INFO - Started process 325 to run task
[2025-02-08T12:29:40.050+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_MusicStreamPipeline.MusicStream_load_time manual__2025-02-08T12:29:37.983005+00:00 [running]> on host 35ef1ca6714b
[2025-02-08T12:29:40.111+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Huynh Thanh Duong' AIRFLOW_CTX_DAG_ID='etl_MusicStreamPipeline' AIRFLOW_CTX_TASK_ID='MusicStream_load_time' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T12:29:37.983005+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-08T12:29:37.983005+00:00'
[2025-02-08T12:29:40.112+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-08T12:29:40.171+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-08T12:29:40.171+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etls/load.py", line 19, in load_dim_Time
    cur.execute(time_table_insert, (row.day_key, row.start_time, row.hour, row.day, row.week, row.month, row.year, row.weekdate))
psycopg2.errors.UndefinedTable: relation "dim_time" does not exist
LINE 1: INSERT INTO dim_time VALUES(2018110100, '2018-11-01 00:00:00...
                    ^

[2025-02-08T12:29:40.179+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl_MusicStreamPipeline, task_id=MusicStream_load_time, execution_date=20250208T122937, start_date=20250208T122939, end_date=20250208T122940
[2025-02-08T12:29:40.187+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 171 for task MusicStream_load_time (relation "dim_time" does not exist
LINE 1: INSERT INTO dim_time VALUES(2018110100, '2018-11-01 00:00:00...
                    ^
; 325)
[2025-02-08T12:29:40.230+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-08T12:29:40.247+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T12:29:40.250+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
